# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

 config.vm.define "Ubuntu1" do |ubuntu|
  ubuntu.vm.box = "ubuntu/xenial64"
  ubuntu.vm.box_check_update = false
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
 end
 config.vm.define "Centos1" do |centos|
  centos.vm.box = "centos/7"
  centos.vm.box_check_update = false
    centos.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
  end
end
